import streamlit as st

def generate_report():
    report = f"""=====================================
KISAN MITRA - FARM REPORT
=====================================
Farm Name: {st.session_state.get('farm_name', 'My Smart Farm')}
Location: {st.session_state.get('farm_location', 'Delhi')}
Farm Size: {st.session_state.get('farm_size', 5.0)} Acres
Primary Crop: {st.session_state.get('primary_crop', 'Wheat')}

--- 🏥 FARM HEALTH ---
Soil Moisture: {st.session_state.get('soil_moisture', 45.0)}%
Soil pH: {st.session_state.get('soil_ph', 6.5)}
Disease Risk: {st.session_state.get('disease_risk', 15)}%

--- 📜 RECENT AI SCANS ---
"""
    history = st.session_state.get("prediction_history", [])
    if history:
        for item in history:
            report += f"- {item['time']}: {item['disease']} ({item['status']})\n"
    else:
        report += "- No recent scans.\n"
        
    report += "\n=====================================\nReport generated by KISAN MITRA Edge AI."
    return report

def profile_ui():
    st.markdown("<h2 style='color: #4ade80;'>👤 Farm Profile & Reports</h2>", unsafe_allow_html=True)
    st.write("Manage your farm details, generate reports, and view the product roadmap.")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("### 📝 Farm Details")
        farm_name = st.text_input("Farm Name", value=st.session_state.get("farm_name", "My Smart Farm"))
        location = st.text_input("Location (City)", value=st.session_state.get("farm_location", "Delhi"))
        farm_size = st.number_input("Farm Size (Acres)", value=st.session_state.get("farm_size", 5.0), step=0.5)
        primary_crop = st.selectbox("Primary Crop", ["Wheat", "Rice", "Maize", "Cotton", "Sugarcane", "Other"], index=0)
        
        if st.button("Save Profile", use_container_width=True):
            st.session_state.farm_name = farm_name
            st.session_state.farm_location = location
            st.session_state.farm_size = farm_size
            st.session_state.primary_crop = primary_crop
            st.success("Profile saved successfully!")
            
        st.markdown("---")
        st.markdown("### 📊 Export Report")
        st.write("Generate a lightweight text summary of your farm's health and AI insights.")
        report_data = generate_report()
        st.download_button(
            label="📄 Download Farm Report (.txt)",
            data=report_data,
            file_name="KisanMitra_Report.txt",
            mime="text/plain",
            use_container_width=True
        )
            
    with col2:
        st.markdown("### 🚀 Future Roadmap")
        st.markdown("""
        <div class="premium-card">
            <p style="color:#8b949e; margin-bottom:5px; font-weight: bold;">Planned Upgrades for KISAN MITRA</p>
            <ul style="list-style-type: none; padding: 0;">
                <li style="margin-bottom: 10px;">🟢 <b>Edge AI Optimizations</b> <span style="color:#4ade80; font-size:0.8em;">(Completed)</span></li>
                <li style="margin-bottom: 10px;">🟢 <b>Smart SaaS Dashboard</b> <span style="color:#4ade80; font-size:0.8em;">(Completed)</span></li>
                <li style="margin-bottom: 10px;">🟡 <b>Arduino IoT Integration</b> <span style="color:#ffd166; font-size:0.8em;">(Q3 Release)</span></li>
                <li style="margin-bottom: 10px;">⚪ <b>Drone Aerial Mapping</b> <span style="color:#8b949e; font-size:0.8em;">(Planned)</span></li>
                <li style="margin-bottom: 10px;">⚪ <b>Automated Irrigation Valves</b> <span style="color:#8b949e; font-size:0.8em;">(Planned)</span></li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
